### ISSUE TITLE
Parse error for getAllFontSizes in pinterest css

### ISSUE THREAD

**Issue by mrmrs** [cssstats/cssstats#172]
Below is the error I am seeing
```
/Users/mrmrs/p/css-averages/node_modules/cssstats/lib/get-all-font-sizes.js:18
        return fontParser(value, '16px serif').size || false
                                              ^
TypeError: Cannot read property 'size' of undefined
    at /Users/mrmrs/p/css-averages/node_modules/cssstats/lib/get-all-font-sizes.js:18:47
    at Array.map (native)
    at Object.module.exports [as getAllFontSizes] (/Users/mrmrs/p/css-averages/node_modules/cssstats/lib/get-all-font-sizes.js:16:8)
    at Object.<anonymous> (/Users/mrmrs/p/css-averages/index.js:35:56)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by johnotander** [comment]
I can confirm the error, and it is occurring in the `cssfontparser` module. I expect we will need to switch over the CSS shorthand expansion to the [`css-shorthand-expand`](https://github.com/kapetan/css-shorthand-expand) module as it appears to be more robust.
