### ISSUE TITLE
Error: Cannot find module "../components/library" 

### ISSUE THREAD

**Issue by zetareticoli** [cssstats/cssstats#253]
Followed your installation instructions but when I type `npm run dev` this is what I get:

cssstats@2.0.0 dev /Users/francesco/Projects/cssstats
next

 DONE  Compiled successfully in 1868ms                                                                                                                                                           15:20:03

Ready on http://localhost:3000
Building page: /

 ERROR  Failed to compile with 2 errors                                                                                                                                                          15:20:16

These relative modules were not found:

../components/library in ./pages/index.js
./library in ./components/Layout.js
(node:4642) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
Error: Cannot find module "../components/library"
    at Object../pages/index.js (/Users/francesco/Projects/cssstats/.next/dist/bundles/pages/index.js:229:7)
    at __webpack_require__ (/Users/francesco/Projects/cssstats/.next/dist/bundles/pages/webpack:/webpack/bootstrap d56e8277aed9ccd1e406?54db:21:1)
    at Object.2 (/Users/francesco/Projects/cssstats/.next/dist/bundles/pages/index.js:414:18)
    at __webpack_require__ (/Users/francesco/Projects/cssstats/.next/dist/bundles/pages/webpack:/webpack/bootstrap d56e8277aed9ccd1e406?54db:21:1)
    at /Users/francesco/Projects/cssstats/.next/dist/bundles/pages/webpack:/webpack/bootstrap d56e8277aed9ccd1e406?54db:68:1
    at Object.<anonymous> (/Users/francesco/Projects/cssstats/.next/dist/bundles/pages/index.js:73:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _callee$ (/Users/francesco/Projects/cssstats/node_modules/next/dist/server/require.js:107:46)
    at tryCatch (/Users/francesco/Projects/cssstats/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/francesco/Projects/cssstats/node_modules/regenerator-runtime/runtime.js:296:22)

**Comment by johno** [comment]
This should now be fixed, thanks for opening an issue!
